name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag spring-boot-app
    - name: Run Test cases
      run: docker run spring-boot-app mvn clean test
    - name: Generate deployment package
      run: zip -r spring-boot-app.zip . -x '*.git*'
    - name: Print directory items
      run: ls -altrh
    - name: Print repository secret
      env:
        AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      run: echo "$AWS_ACCESS_KEY_SECRET"
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        applicaton_name: demo-app-2
        environment_name: Demo-app-2-dev
        version_label: 12345
        region: ap-south-1
        deployment_package: spring-boot-app.zip

