name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag spring-boot-app
    - name: Run Test cases
      run: docker run spring-boot-app mvn clean test
    - name: Generate deployment package
      run: zip -r spring-boot-app.zip . -x '*.git*'
    - name: Print directory items
      run: ls -altrh
    - name: Print env variable
      run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}
